version: '3'

services:
  mongo:
    image: mongo:3.4
    container_name: mongoDB

  mongo-seed:
    container_name: mongo-seed
    image: fvilers/mongo-seed
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./database:/database
    command:
      "mongoimport --host mongo --port 27017 --db airport --mode upsert --type json --file database/airport.json --jsonArray --drop"
    depends_on:
      - mongo

  api:
    image: bladeours/airport-api
    ports:
      - "8081:8081"
    container_name: airport-api


